#ifndef NEXUSOS_SYSCALL_ABI_H
#define NEXUSOS_SYSCALL_ABI_H

#include <stdint.h>

/* Stable NexusOS Ring-3 syscall ABI. Keep numeric assignments append-only. */
enum nexus_syscall_number {
    NEXUS_SYS_NOP = 0,
    NEXUS_SYS_EXIT = 1,
    NEXUS_SYS_GETPID = 2,
    NEXUS_SYS_WRITE = 3,
    NEXUS_SYS_CLOSE = 4,
    NEXUS_SYS_GETPPID = 5,
    NEXUS_SYS_OPEN = 6,
    NEXUS_SYS_READ = 7,
    NEXUS_SYS_SEEK = 8,
    NEXUS_SYS_TELL = 9,
    NEXUS_SYS_STAT = 10,
    NEXUS_SYS_MKDIR = 11,
    NEXUS_SYS_RMDIR = 12,
    NEXUS_SYS_UNLINK = 13,
    NEXUS_SYS_RENAME = 14,
    NEXUS_SYS_GETCWD = 15,
    NEXUS_SYS_CHDIR = 16,
    NEXUS_SYS_PROCESS_ENUM = 17,
    NEXUS_SYS_WAITPID = 18,
    NEXUS_SYS_GETPRIORITY = 19,
    NEXUS_SYS_SETPRIORITY = 20,
    NEXUS_SYS_GETNAME = 21,
    NEXUS_SYS_SETNAME = 22,
    NEXUS_SYS_EXEC = 23,
    NEXUS_SYS_MMAP = 24,
    NEXUS_SYS_MUNMAP = 25,
    NEXUS_SYS_BRK = 26,
    NEXUS_SYS_GETCPUTICKS = 27,
    NEXUS_SYS_GETSTARTTICK = 28,
    NEXUS_SYS_GETUPTIME_MS = 29,
    NEXUS_SYS_PROCESS_COUNT = 30,
    NEXUS_SYS_ZOMBIE_COUNT = 31,
    NEXUS_SYS_GETENV = 32,
    NEXUS_SYS_SETENV = 33,
    NEXUS_SYS_UNSETENV = 34,
    NEXUS_SYS_FD_COUNT = 35,
    NEXUS_SYS_MEMINFO = 36,
    NEXUS_SYS_GETTID = 37,
    NEXUS_SYS_GETVERSION = 38,
    NEXUS_SYS_GETARCH = 39,
    NEXUS_SYS_GETPAGESIZE = 40,
    NEXUS_SYS_GETUSERBASE = 41,
    NEXUS_SYS_GETUSERLIMIT = 42,
    NEXUS_SYS_GETSTACKTOP = 43,
    NEXUS_SYS_GETHEAPBASE = 44,
    NEXUS_SYS_GETHEAPEND = 45,
    NEXUS_SYS_GETFDTYPE = 46,
    NEXUS_SYS_GETFDOFFSET = 47,
    NEXUS_SYS_GETFD_FLAGS = 48,
    NEXUS_SYS_GETQUANTUM_EXPIRATIONS = 49,
    NEXUS_SYS_GETCONTEXT_SWITCHES = 50,
    NEXUS_SYS_GETTIMER_HZ = 51,
    NEXUS_SYS_GETQUANTUM_TICKS = 52,
    NEXUS_SYS_GETTHREAD_COUNT = 53,
    NEXUS_SYS_GETMAX_THREADS = 54,
    NEXUS_SYS_GETREADY_COUNT = 55,
    NEXUS_SYS_GETSLEEPING_COUNT = 56,
    NEXUS_SYS_GETTHREAD_SWITCHES = 57,
    NEXUS_SYS_GETTHREAD_RUNTIME = 58,

    /* Nexus Native Runtime / IPC ABI introduced in 0.7. */
    NEXUS_SYS_RUNTIME_INFO = 59,
    NEXUS_SYS_CHANNEL_CREATE = 60,
    NEXUS_SYS_CHANNEL_CLOSE = 61,
    NEXUS_SYS_CHANNEL_SEND = 62,
    NEXUS_SYS_CHANNEL_RECV = 63,
    NEXUS_SYS_CHANNEL_POLL = 64,
    NEXUS_SYS_GETCAPS = 65,
    NEXUS_SYS_HAS_CAP = 66,
    NEXUS_SYS_DROP_CAP = 67
};

#define NEXUS_SYSCALL_ABI_VERSION 1u
#define NEXUS_CHANNEL_MESSAGE_MAX 256u
#define NEXUS_CHANNEL_QUEUE_DEPTH 8u
#define NEXUS_PROCESS_CHANNELS 8u

#endif
